### ISSUE TITLE
update publications page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1847]
https://www.pombase.org/about/published-by-pombase

to include new pombase, japonics and PHI-base publications.

- The japonicus paper should be listed as a Pombase paper since we are first and final author. It is collaborative but essentially a PB paper.

The citing PomBase 
https://www.pombase.org/about/citing-pombase
should change to the new manuscript

**Comment by kimrutherford** [comment]
I'll update this page too: https://www.japonicusdb.org/about/published-by-japonicusdb

**Comment by kimrutherford** [comment]
The JaponicusDB paper doesn't seem to be indexed in PubMed so I'll add that link later.

**Comment by kimrutherford** [comment]
Done!  The PomBase pages have been updated.  The japonicusdb.org page will be updated by Wednesday morning.

Let me know if you spot any problems.

I'll leave this open until the PMID for the JaponicusDB paper is available.

**Comment by ValWood** [comment]
Since there are no Japonicus staff I wonder if the header should change.

JaponicusDB  publications 
Would be OK, and would work for PomBase too. I also hate the word "staff" -  it sounds as though we work in a country house.

**Comment by kimrutherford** [comment]
> I also hate the word "staff" - it sounds as though we work in a country house.

:-)

Yep, I agree.  I'll change it.

**Comment by kimrutherford** [comment]
I've changed the headers to "JaponicusDB publications" and "PomBase publications".

**Comment by ValWood** [comment]
I'mm close this. The Japonicus paper still isn't indexed for Pubmud, But I will see it when it is and alert you
