### ISSUE TITLE
Full view extension presentation on phosphorylation phenotypes 

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2272]
In these cases we could group 

like
cdc2-33(A177T aa) affecting cdc18  modified residue T10A,T46A,T60AT104A,T134A 
cdc2-33(A177T aa) affecting rap1 modified residue T378,S422,S513
etc

<img width="809" alt="Screenshot 2024-11-11 at 08 12 06" src="https://github.com/user-attachments/assets/77fdc5b4-571b-4e1b-beae-5239dd9a8ce9">

**Comment by kimrutherford** [comment]
Yep, we can do that.  If I change the configuration so that residue extensions can be grouped together I get this: 

![image](https://github.com/user-attachments/assets/4ee5be13-724a-4372-b4ac-85b571382feb)

https://desktop.kmr.nz/gene/SPBC11B10.09

We also have `assay_using` configured to group together so there are also summaries that look like this:

![image](https://github.com/user-attachments/assets/60a6285e-b5b4-4985-8cfd-a9f1b1e6d815)

https://dev.pombase.org/gene/SPBC530.14c

Is that OK?

**Comment by ValWood** [comment]
Not sure. @PCarme  is it clear  that the residue belongs to the preceding ID in the list?

Also in the first figure, by grouping be residue, we lose

cdc2-33(A177T aa) affecting cdc13, orc2, sld3
cdc2-L7(P208S aa) affecting cdc13, orc2

grouping

ideally it would be
allele  plus affecting + residue (when multiple residues, or single residue)
cdc2-33(A177T aa) affecting cdc18 modified residue T10A,T46A,T60AT104A,T134A
cdc2-33(A177T aa) affecting rap1 modified residue T378,S422,S513
cdc2-33(A177T aa) affecting xxx1 modified residue Txxx
THEN
all of the ones  for the same allele which have no residue
cdc2-33(A177T aa) affecting cdc13, orc2, sld3

then the same for each allele

Is that possible?

I think people will primarily want  the same allele together, then the most compacted version of that information.
At  the moment you need to look at the entire list to see the affects of a single allele.

**Comment by PCarme** [comment]
> is it clear that the residue belongs to the preceding ID in the list?

It is clear to me at least, although it feels a bit awkward.

> ideally it would be allele plus affecting + residue (when multiple residues, or single residue) 
cdc2-33(A177T aa) affecting cdc18 modified residue T10A,T46A,T60AT104A,T134A 
cdc2-33(A177T aa) affecting rap1 modified residue T378,S422,S513 
cdc2-33(A177T aa) affecting xxx1 modified residue Txxx 
THEN all of the ones for the same allele which have no residue 
cdc2-33(A177T aa) affecting cdc13, orc2, sld3
> 
> then the same for each allele

I agree, this would be a better solution overall

**Comment by kimrutherford** [comment]
Sorry, I realise that I got this wrong.  The [screenshot for cdc2](https://github.com/pombase/website/issues/2272#issuecomment-2469436413) shows the residues grouped together but that was from when I had mis-configured my desktop site.

Adding the configuration to group by "modified residue" doesn't work in this case because (I now realise) it's not possible to group by two different extension relations in the same annnotation.  The code doesn't support that.  It's tricky code so I can't say how long this will take to fix.  I've having a look now.

**Comment by kimrutherford** [comment]
> Adding the configuration to group by "modified residue" doesn't work in this case because (I now realise) it's not possible to group by two different extension relations in the same annotation. The code doesn't support that.

I think I've fixed that, more or less.  There might still be some situations where the grouping doesn't happen, but I think most cases will be covered.  The change will be on pombase.org in the morning.

**Comment by kimrutherford** [comment]
![image](https://github.com/user-attachments/assets/8935b13d-e202-4f57-97b9-72a8c3e9c209)

**Comment by ValWood** [comment]
Fantastic. We will look it over and then we can also use the same configuration for other terms which have extensions and residues (if not already).

That would be all children of
abnormal protein modification (FYPO:0002494)
and
normal protein modification (FYPO:0002495)

**Comment by ValWood** [comment]
So in the figure above I still see 3 rows for cdc2-33 affecting cdc18 
ie 
T104A, T10A, T134A
T46A, T60A
T374A

**Comment by kimrutherford** [comment]
> So in the figure above I still see 3 rows for cdc2-33 affecting cdc18

Yep, there are still have cases that aren't collected together.  It's tricky to get it working in all situations, but I'll have a look at that one tomorrow.

**Comment by kimrutherford** [comment]
> It's tricky to get it working in all situations, but I'll have a look at that one tomorrow.

I re-wrote the code to handle more cases.  This change will be on pombase.org soon:

![image](https://github.com/user-attachments/assets/b0d60d42-6cab-4ea6-837d-6a0cfd92b302)

**Comment by kimrutherford** [comment]
>  This change will be on pombase.org soon

It's there now.  Let me know if you spot any problems.  It's new code which makes bugs more likely.

**Comment by ValWood** [comment]
Amazing.  That's brillaint!

**Comment by kimrutherford** [comment]
I'll close this.  Please open new issues if you see any bugs or other weirdness.
